# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Publish an application installer

on:
  push:
    tags:
      - "v*"

jobs:
  build:

    runs-on: windows-latest
    # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20.15.0
        cache: 'npm'
    - run: npm install -g yarn
    - run: yarn install
    - run: yarn build
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: git tag v24.06.30
    - run: git push origin v24.06.30
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: dist/*.exe
